require("prototypes.item-group")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.quality")
require("prototypes.technology")
require("prototypes.module")
require("prototypes.bacteria-modifications")